/* eslint-disable @next/next/no-page-custom-font */
import React from 'react';
import Head from 'next/head'
//import Image from 'next/image'
//import { Inter } from '@next/font/google'
//import styles from '@/styles/Home.module.css'
import { Button } from '@material-ui/core'

//const inter = Inter({ subsets: ['latin'] })


import User from "../layouts/user";
import Class from "../layouts/class";
import Tag from "../layouts/tag";

import Info from "../layouts/info";
import Time from "../layouts/time";

import Main from "../layouts/main";


import Container from "@material-ui/core/Container";
import Grid from "@material-ui/core/Grid";





export default function Home({tag,class_,markdown}:any) {
  //console.log(tag)
  const data = {tag:tag.data.length,
    class_:class_.data.length}

  
   
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta
  name="viewport"
  content="minimum-scale=1, initial-scale=1, width=device-width"
/>
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" />
      </Head>


      <main>


        {/* <FormControlLabel
          control={<Switch checked={checked} onChange={handleChange} />}
          label="Show"
        /> */}
        <Container>
      
				<Grid container spacing={3}>
					<Grid item xs={12} sm={3}>
						<User data={data}></User>
						<Class data={class_}></Class>
						<Tag data={tag}></Tag>
					</Grid>
					<Grid item xs={12} sm={6}>
						<Main data={markdown}></Main>
					</Grid>
					<Grid item xs={12} sm={3}>
						<Info></Info>
						<Time></Time>
					</Grid>
				</Grid>
			</Container>

     

      </main>
    </>
  )
}

export async function getStaticProps() {
	// 调用外部 API 获取内容
	const tagData = await fetch('http://127.0.0.1:7412/api/tag')
	const tag = await tagData.json()

  const classData = await fetch('http://127.0.0.1:7412/api/class')
	const class_ = await classData.json()
  

  const markdownData = await fetch('http://127.0.0.1:7412/api/markdown')
  const markdown = await markdownData.json()

	// 在构建时将接收到 `posts` 参数
	return {
	  props: {
		tag,
    class_,
    markdown
	  },
	}
  }
