/* eslint-disable @next/next/no-sync-scripts */
/** @format */

import React, { useContext } from "react";
import { createTheme, ThemeProvider } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import Header from "./header";
import Search from "./search";

import Head from "next/head";
import Context from "@/context/global";

export default function Layout({ children }: any) {
	const { theme } = useContext(Context);

	const light = createTheme({
		palette: {
			mode: "light",
		},
	});
	const dark = createTheme({
		palette: {
			mode: "dark",
     
		},
	});

	return (
		<>
			<Head>
				<title>757909</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			
			<div
				className='layout_container'
				style={{
					backgroundImage: `url(${theme ? "light_bg.jpg" : "dark_bg.jpg"})`,
				}}
			>
				<ThemeProvider theme={theme ? light : dark}>
					<CssBaseline />
					<Search></Search>
					<Header></Header>

					{children}
				</ThemeProvider>
			</div>
		</>
	);
}
