import React, { useState,useEffect, useLayoutEffect, useRef } from 'react'

import { createTheme, ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import Box from '@mui/material/Box';
import Container from '@mui/material/Container';
import Header from './header'
import Search from './search';

import Head from 'next/head'
import { getToken, setToken } from '@/utils/token';

import light from "public/light_bg.jpeg"


export default function Layout({children}:any) {

    const [open,setOpen] = useState(false)
    const [bgImage,setBgImage] = useState('light_bg.jpeg')

    const handleSearch=(val:any)=>{
        
        val?setOpen(true):''
    }
    const setSearchDialog = (val:any)=>{
        setOpen(val)
    }

    const [theme,setTheme]= useState(createTheme({
        palette: {
            mode: 'light',
          },
      }))

    const handleTheme = (val:any)=>{

        // container.current.style.backgroundImage= "url('../../public/dark_bg.jpeg')"
        val?setBgImage('light_bg.jpeg'):setBgImage('dark_bg.jpeg')
        setTheme(createTheme({
            palette: {
                mode: val?'light':'dark',
              },
          }))

          //console.log("object");
    }


  return (
    <>
     <Head>
        <title>757909</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div className='layout_container' style={{backgroundImage:`url(${bgImage})`}}>
    <ThemeProvider theme={theme}>
        <CssBaseline />
        <Search open={open} setSearchDialog={setSearchDialog}></Search>
        <Header handleSearch=
        {handleSearch} handleTheme={handleTheme}></Header>

        {children}
      </ThemeProvider>
     

    </div>
    </>
  )
}
